version: '3'
services:
    hwatchdog:
        image: hwatchdog-s:latest
        container_name: wdss
        ports: 
            - 9001:9001
    ui:
        image: hwatchdog-ui:latest
        container_name: wdui
        ports: 
            - 9002:80


